## Dockerfile for ROSARUM in AFL mode.

FROM ubuntu:22.04

LABEL maintainer="alexandre.doyen@cea.fr"
LABEL description="Docker image for the ROSARUM backdoor detection benchmark, with AFL++ instrumented binaries"

RUN apt-get clean && apt-get update

# Install target program dependencies.
RUN apt-get update && apt-get install -y autoconf autogen automake bison build-essential cmake \
    libasound2-dev libboost-all-dev libbrotli-dev libbz2-dev libcap-dev libdeflate-dev \
    libflac-dev libharfbuzz-dev libjbig-dev libjpeg-dev liblerc-dev liblcms2-dev liblzma-dev \
    libmp3lame-dev libmpg123-dev libogg-dev libopenjp2-7-dev libopus-dev libpam-dev \
    libsqlite3-dev libssl-dev libtiff-dev libtool libvorbis-dev libwebp-dev libxml2-dev \
    libzstd-dev netcat-traditional pkg-config re2c zip
# Install tclsh, needed by the SQLite3 benchmark.
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y tclsh

# Install AFL++ to have access to afl-cc and co
RUN apt-get install -y build-essential python3-dev automake cmake git flex bison \
    libglib2.0-dev libpixman-1-dev python3-setuptools cargo libgtk-3-dev
RUN apt-get install -y lld-14 llvm-14 llvm-14-dev clang-14 || sudo apt-get install -y lld llvm llvm-dev clang
RUN apt-get install -y gcc-$(gcc --version|head -n1|sed 's/\..*//'|sed 's/.* //')-plugin-dev libstdc++-$(gcc --version|head -n1|sed 's/\..*//'|sed 's/.* //')-dev
RUN apt-get install -y wget unzip

WORKDIR /root/
RUN wget https://github.com/AFLplusplus/AFLplusplus/archive/refs/tags/v4.30c.zip -O aflplusplus-v4.30c.zip
RUN unzip aflplusplus-v4.30c.zip
RUN cd AFLplusplus-4.30c && make source-only
RUN cd AFLplusplus-4.30c && make install

# Build all target programs in all 3 variants in AFL-instrumented mode
WORKDIR /root/rosarum/
COPY targets/ .
RUN make all-afl

# Clean by removing all non-AFL-compatibles targets
RUN for TARGET in `grep -L all-afl */*/Makefile`; do TARGET_PATH=`dirname $TARGET`; rm -rf $TARGET_PATH; done